name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        recipe: ['i-i-o-oscilloscope.rb','libad9361-iio.rb','libiio.rb']
        release: ["", "--HEAD"]

    steps:
      - uses: actions/checkout@v2

      - name: Update brew
        if: ${{ always() }}
        run: brew update

      - name: Build and test recipe
        if: ${{ always() }}
        run: |
          brew install -v ${{ matrix.release }} --build-from-source ./${{ matrix.recipe }}
          brew test
