name: Build

on: [push, pull_request]

jobs:
  install:

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-10.15, macos-11.0 ]
        package: [ libiio, libad9361-iio, gr-iio, iio-oscilloscope ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Copy formulae
      run: cp *.rb $(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/
    - name: Install
      run: |
        [ "${{ matrix.package }}" == "gr-iio" ] && OPTIONS="--HEAD"
        [ "${{ matrix.package }}" != "libiio" ] && brew install --verbose --build-from-source libiio
        [ "${{ matrix.package }}" == "iio-oscilloscope" ] && brew install --verbose --build-from-source libad9361-iio
        [ "${{ matrix.package }}" == "gr-iio" ] && brew install --verbose --build-from-source libad9361-iio
        brew install --verbose --build-from-source $OPTIONS ${{ matrix.package }}
    - name: Test
      run: brew test ${{ matrix.package }}
